In [7]:
import pandas as pd

# Read actual silo readings and historical averages
actual_df = pd.read_csv("/content/silo_actuals (1).csv", sep=",", keep_default_na=False)
average_df = pd.read_csv("/content/historical_averages (1).csv", sep=",", keep_default_na=False)

# Create date range for June 2023
date_range = pd.date_range(start="2023-06-01", end="2023-06-30")

# Initialize lists to store data
output_data = []
running_total = 0
weekly_total = 0
weekly_start_date = None

# Loop through each date in the range
for date in date_range:
    # Check if there's an actual silo reading for the date
    actual_reading = actual_df[actual_df['date'] == date.strftime('%m/%d/%Y')]['silo_wt_in_tons']

    if not actual_reading.empty:
        silo_wt_in_tons = int(actual_reading)
    else:
        # Use historical average for that day of the week
        day_of_week = date.strftime('%A')
        historical_average = int(average_df[average_df['day'] == day_of_week]['average_tons'])
        silo_wt_in_tons = historical_average

    # Calculate running total tons
    running_total += silo_wt_in_tons

    # Check if it's Wednesday to update weekly total tons
    if date.strftime('%A') == 'Wednesday':
        weekly_total += silo_wt_in_tons
        weekly_start_date = date

    # Append data to output list
    output_data.append({
        'date': date.strftime('%m/%d/%Y'),
        'silo_wt_in_tons': silo_wt_in_tons,
        'weekly_total_tons': weekly_total if date.strftime('%A') == 'Wednesday' else '',
        'mtd_running_total_tons': running_total,
        'monthly_grand_total': ''
    })

# Calculate monthly grand total
monthly_grand_total = running_total

# Update the last entry with the monthly grand total
output_data[-1]['monthly_grand_total'] = monthly_grand_total

# Convert output data to DataFrame
output_df = pd.DataFrame(output_data)

# Print the DataFrame
print(output_df)

# Save the DataFrame to a CSV file
output_df.to_csv("/content/output_report2.csv", index=False)

          date  silo_wt_in_tons weekly_total_tons  mtd_running_total_tons  \
0   06/01/2023               80                                        80
1   06/02/2023               65                                       145
2   06/03/2023               45                                       190
3   06/04/2023               40                                       230
4   06/05/2023               50                                       280
5   06/06/2023               65                                       345
6   06/07/2023               70                70                     415
7   06/08/2023               80                                       495
8   06/09/2023               65                                       560
9   06/10/2023               45                                       605
10  06/11/2023               40                                       645
11  06/12/2023               50                                       695
12  06/13/2023               65                                       760
13  06/14/2023               70               140                     830
14  06/15/2023               80                                       910
15  06/16/2023               65                                       975
16  06/17/2023               45                                      1020
17  06/18/2023               40                                      1060
18  06/19/2023               50                                      1110
19  06/20/2023               65                                      1175
20  06/21/2023               70               210                    1245
21  06/22/2023               80                                      1325
22  06/23/2023               65                                      1390
23  06/24/2023               45                                      1435
24  06/25/2023               40                                      1475
25  06/26/2023               50                                      1525
26  06/27/2023               65                                      1590
27  06/28/2023               70               280                    1660
28  06/29/2023               80                                      1740
29  06/30/2023               65                                      1805

   monthly_grand_total
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29                1805